nm1 = int(input("digite a nota da primeira prova"))
nm2 = int(input("digite a nota de segunda prova"))
nb = ((nm1+nm2)/2)
print (f"sua nota bo primeiro bimestre é {nb}")
nm3 = int(input("digite a nota da terceira prova"))
nm4 = int(input("digite a nota da quarta prova"))
nb2 = ((nm3+nm4)/2)
print (f"sua nota bo segundo bimestre é {nb2}")
nf = ((nb+nb2)/2)
print (f"a nota semestre {nf}")
